name: Detect Merge Bypass
description: Detect if a merge bypassed required checks.
inputs:
  github_token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  owner:
    description: 'Owner of the repository'
    required: false
    default: '${{ github.repository_owner }}'
  repo:
    description: 'Name of the repository'
    required: false
    default: '${{ github.event.repository.name }}'
  sha:
    description: 'SHA of the commit to check'
    required: false
    default: '${{ github.sha }}'
  fail_on_bypass_detected:
    description: 'Fail the action if a merge bypassed required checks'
    required: false
    default: false
    
outputs:
  merge_bypass_detected:
    description: 'True if a merge bypassed required checks'
  commit_actor:
    description: 'The actor who made the commit'
  commit_from_pr:
    description: 'True if the commit is from a pull request'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'red'